import { FC } from "react";
import Head from "next/head";

interface Props {
  title: string;
}

import React from 'react'
import { Footer } from "../ui";

export const AuthLayout: FC<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto min-h-screen">
        <div className="max-w-md mx-auto px-4">
          <h2 className="text-center text-dark mt-5 text-2xl font-bold">
            Bienvenido
          </h2>
          <div className="text-center mb-5 text-dark text-lg">
            Next Template
          </div>
          {children}
        </div>
      </main>
      <Footer/>
    </>
  );
}

export default AuthLayout;
