import { FC } from 'react';
import Head from "next/head";
import { Footer, Navbar } from "../ui";
// import { StatusCheck } from '../../helpers/StatusCheck';

interface Props {
    title: string;
}

export const PublicLayout: FC<Props> = ({ children, title }) => {
  return (
    <>
      {/* <StatusCheck /> */}
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main className="container mx-auto mt-5 min-h-screen">{children}</main>
      <Footer/>
    </>
  );
};